### ISSUE TITLE
Instructions out of sync with Dark Reader 4.9.96

### ISSUE THREAD

**Issue by CBroz1** [Dpbm/Dracula-DarkReader#4]
The current DarkReader UI has moved the dev tools button:

![image](https://github.com/user-attachments/assets/dfb8729c-358c-4f22-9512-90ba9a7908be)

Now, you click More ->All Settings -> Advanced -> Dev Tools -> Advanced -> Preview New Design

**Comment by Dpbm** [comment]
Thanks @CBroz1, I appreciate your collaboration 🙏

I've added you as a contributor on `readme.md`.
